### ISSUE TITLE
Balance term implement

### ISSUE THREAD

**Issue by SikaStar** [huitangtang/SRDC-CVPR2020#5]
Hi, how do you implement the balance term (e.g. the second term) in Eq. (1) and Eq. (5)? I can not find the corresponding code.
![image](https://user-images.githubusercontent.com/26598342/93333918-a3f77180-f856-11ea-9df0-8d77263f7a88.png)

**Comment by huitangtang** [comment]
![image](https://user-images.githubusercontent.com/42053362/93410351-68e35580-f8cb-11ea-95f3-0d8f36204cb0.png)
Hi, there is no code for every single term in Eq. (1). We have derived its closed-form solution (see the above image). Please refer to "Deep clustering via joint convolutional autoencoder embedding and relative entropy minimization" for more details of the derivation.

**Comment by SikaStar** [comment]
Got it! Thanks very much


| |
yongxingdai
|
|
yongxingdai@163.com
|
签名由网易邮箱大师定制
On 9/17/2020 09:56，HuiTang<notifications@github.com> wrote：


Hi, there is no code for every single term in Eq. (1). We have derived its closed-form solution (see the above image). Please refer to "Deep clustering via joint convolutional autoencoder embedding and relative entropy minimization" for more details of the derivation.
